app:
  build: .
  container_name: georedis_app
  links:
    - redis:redisdb
  volumes:
    - .:/data/app
  command: bash docker-runserver.sh

redis:
  image: redis:3.2
  container_name: georedis_redis
